# Generated by Django 3.1.5 on 2021-01-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='category_id',
            new_name='product_id',
        ),
    ]
