# Generated by Django 3.1.5 on 2021-01-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20210113_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='product_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='models.product'),
        ),
    ]
